skillMetadata:
  sections:
  - name: Login
    fields:
    - name: host
      type: text
      label: Host adress or ip number
      value: ''
    - name: token
      type: password
      label: Access Token (See 'developer' tab of the gateway.)
      value: ''
