skillMetadata:
  sections:
  - name: Login
    fields:
    - name: host
      type: text
      label: Host adress or ip number
      value: ''
    - name: token
      type: password
      label: Access Tokens (See 'developer' tab of the gateway.)
      value: ''
  - name: Options
    fields:
    - name: enable_fallback
      type: checkbox
      label: Enable conversation component as fallback
      value: "true"
